"""Markdown reporter — for GitHub PR comments and docs."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

    from decibench.models import SuiteResult


class MarkdownReporter:
    """Generate Markdown report for PR comments."""

    @staticmethod
    def report(result: SuiteResult, output_path: Path | None = None) -> str:
        """Generate Markdown report string."""
        score = result.decibench_score

        lines: list[str] = [
            "## Decibench Quality Report",
            "",
            f"**Score: {score}/100** | "
            f"{result.passed}/{result.total_scenarios} passed | "
            f"{result.duration_seconds:.1f}s",
            "",
            f"Target: `{result.target}` | Suite: `{result.suite}`",
            f"Judge: `{result.judge_model or 'none'}`",
            "",
            "### Score Breakdown",
            "",
            "| Category | Score | Weight |",
            "|----------|------:|-------:|",
            *[
                f"| {cat.replace('_', ' ').title()} "
                f"| {result.score_breakdown.get(cat, 50.0):.0f}/100 | {w}% |"
                for cat, w in [
                    ("task_completion", 25), ("latency", 20), ("audio_quality", 15),
                    ("conversation", 15), ("robustness", 10), ("interruption", 10),
                    ("compliance", 5),
                ]
            ],
            "",
            "### Metrics",
            "",
            "| Metric | Value | Status |",
            "|--------|------:|:------:|",
        ]

        # Aggregate metrics
        metric_agg: dict[str, tuple[float, str, bool]] = {}
        display_names = {
            "turn_latency_p50_ms": "Latency P50",
            "turn_latency_p95_ms": "Latency P95",
            "wer": "WER",
            "mos_ovrl": "Audio Quality (MOS)",
            "task_completion": "Task Completion",
            "pii_violations": "PII Violations",
            "ai_disclosure": "AI Disclosure",
            "compliance_score": "Compliance",
        }

        for r in result.results:
            for name, metric in r.metrics.items():
                if name in display_names:
                    if name not in metric_agg:
                        metric_agg[name] = (0.0, metric.unit, True)
                    old_sum, unit, old_pass = metric_agg[name]
                    metric_agg[name] = (
                        old_sum + metric.value,
                        unit,
                        old_pass and metric.passed,
                    )

        count = max(len(result.results), 1)
        for key in display_names:
            if key in metric_agg:
                total, unit, passed = metric_agg[key]
                avg = total / count
                status = "Pass" if passed else "**FAIL**"
                unit_str = f" {unit}" if unit and not unit.startswith("/") else unit
                lines.append(
                    f"| {display_names[key]} | {avg:.1f}{unit_str} | {status} |"
                )

        # Failed scenarios
        failed = [r for r in result.results if not r.passed]
        if failed:
            lines.extend([
                "",
                "### Failed Scenarios",
                "",
            ])
            for r in failed[:10]:
                lines.append(f"- **{r.scenario_id}**: {', '.join(r.failures[:2])}")

        lines.extend([
            "",
            f"*Generated by [Decibench](https://decibench.dev) v{result.decibench_version}*",
        ])

        md = "\n".join(lines)

        if output_path:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(md)

        return md
